// A CERT-In incident report DRAFT (plan §3.10), made when a TAMPER or INTEGRITY_CRITICAL incident reaches the regulator rung. CERT-In's
// Directions of 28 April 2022 (section 70B(6), IT Act 2000) ask for cyber incidents to be reported within 6 hours of being noticed.
// This fills in what Saakshi knows and leaves the rest blank for a responsible officer. Saakshi files nothing. Browser-safe.
import type { Incident, IncidentKind } from '@saakshi/core/ops';
import { blastText, dcName } from './incidents.ts';

const esc = (s: unknown): string => String(s).replace(/[&<>"']/g, (c) => `&#${c.charCodeAt(0)};`);
const iso = (ms: number): string => new Date(ms).toISOString();
const TYPE: Partial<Record<IncidentKind, string>> = {
  TAMPER: 'Unauthorised modification of exam records (data integrity)',
  INTEGRITY_CRITICAL: 'Unauthorised access or remote-control software at an exam seat',
};

export function certInHtml(i: Incident, o: { exam: string; shift: string; now: number }): string {
  const blank = '<span class="blank">&nbsp;</span>';
  const facts: [string, string][] = [
    ['Incident id (Saakshi)', i.id], ['Examination and shift', `${o.exam} · ${o.shift}`], ['Type', TYPE[i.kind] ?? i.kind], ['Severity', i.severity],
    ['Noticed at (UTC)', iso(i.openedAt)], ['Report due by (6 hours after noticing, UTC)', iso(i.openedAt + 6 * 3_600_000)],
    ['Affected systems', [...i.blast.cells.map(dcName), `${i.blast.centres.length} centre(s): ${i.blast.centres.join(', ') || '—'}`].join('; ')],
    ['Scope', blastText(i.blast)], ['What was observed', `${i.title}. ${i.detail}`],
    ['Escalation so far', i.ladder.map((l) => `${l.rung} at ${iso(l.at)}`).join('; ') + (i.ack ? `; acknowledged by ${i.ack.by} (${i.ack.rung}) at ${iso(i.ack.at)}` : '; not acknowledged')],
    ['Evidence held', i.cand ? 'the evidence pack for the affected candidate (control → Evidence) and the cells\' evidence tables' : 'the cells\' evidence tables and control\'s custody log'],
  ];
  return `<!doctype html>
<html lang="en"><head><meta charset="utf-8"><title>CERT-In report draft — ${esc(i.id)}</title>
<style>body{font:1rem/1.5 system-ui,sans-serif;color:#202124;max-width:56rem;margin:1.5rem auto;padding:0 1rem}h1{font-size:1.563rem}h2{font-size:1.25rem}
table{border-collapse:collapse;width:100%}th,td{border:1px solid #9aa0a6;padding:.25rem .5rem;text-align:left;vertical-align:top}
.note{border:2px solid #b06000;background:#fef7e0;padding:.5rem .75rem}.blank{display:inline-block;min-width:16rem;border-bottom:1px solid #202124}</style></head><body>
<h1>Cyber security incident report — DRAFT TEMPLATE</h1>
<p class="note">Generated by Saakshi at ${esc(iso(o.now))} when incident ${esc(i.id)} reached the regulator rung. It has not been filed. CERT-In's Directions of 28 April 2022 ask for a report within 6 hours of noticing an incident (here by ${esc(iso(i.openedAt + 6 * 3_600_000))}). Check CERT-In's current form and channel, complete the blanks, and have a responsible officer file it.</p>
<h2>What Saakshi recorded</h2>
<table>${facts.map(([k, v]) => `<tr><th scope="row">${esc(k)}</th><td>${esc(v)}</td></tr>`).join('\n')}</table>
<h2>To be completed by the reporting officer</h2>
<p>Reporting organisation: ${blank}</p><p>Name and designation: ${blank}</p><p>Phone and e-mail: ${blank}</p>
<p>IP addresses, hosts and logs attached: ${blank}</p><p>Containment actions taken: ${blank}</p><p>Signature and date: ${blank}</p>
</body></html>
`;
}
